[package]
name = "white-hole"
version.workspace = true
authors.workspace = true
description = "Fxxk You Edge"
edition.workspace = true

[build-dependencies.reqwest]
features = ["blocking"]
workspace = true

[build-dependencies.tauri-build]
features = []
version = "2.6.2"

[dependencies]
base64 = "0.22"
colored = "3.1.1"
delay_timer = "0.11.6"
minisign-verify = "0.2"
error_set = { workspace = true }
get-data-url = "0.3"
log = { workspace = true }
percent-encoding = "2.3.2"
reqwest = { workspace = true }
scc = { workspace = true }
serde_json = { workspace = true }
tauri-plugin-deep-link = "2"
tauri-plugin-log = "2.8.0"
tauri-plugin-notification = "2.3.3"
url = "2.5.8"

[dependencies.cached]
features = ["async"]
version = "0.59.0"

[dependencies.downloader]
rev = "1163b7ba8e9b592867b19b3919b2c99614f3de30"
git = "https://github.com/thlstsul/downloader"

[dependencies.fern]
features = ["colored"]
version = "0.7"

[dependencies.publicsuffix]
features = ["std"]
version = "2.3.0"

[dependencies.serde]
workspace = true

[dependencies.sqlx]
features = [
    "runtime-tokio",
    "sqlite",
    "time",
]
version = "0.8.6"

[dependencies.tauri]
features = [
    "devtools",
    "tray-icon",
    "unstable",
]
version = "2.11.2"

[dependencies.time]
features = [
    "macros",
    "serde",
    "std",
]
workspace = true

[dependencies.tokio]
features = ["fs", "time"]
version = "1"

[dependencies.uuid]
features = [
    "js",
    "serde",
    "v7",
]
version = "1"

[lib]
crate-type = [
    "cdylib",
    "rlib",
    "staticlib",
]
name = "white_hole_lib"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2.4"
tauri-plugin-updater = "2"
tauri-plugin-window-state = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies.hotkey]
path = "../hotkey"

[target."cfg(windows)".dependencies]
tauri-winrt-notification = "0.7.2"
webview2-com = "0.38"
windows = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_Com", "Win32_System_DataExchange", "Win32_System_Diagnostics_ToolHelp", "Win32_System_LibraryLoader", "Win32_System_Memory", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
