[package]
name = "hotkey"
version.workspace = true
edition.workspace = true

[dependencies]
error_set = { workspace = true }
inventory = "0.3.24"
keyboard-types = "0.8.3"
log = { workspace = true }
scc = { workspace = true }

[dependencies.hotkey-macros]
path = "../hotkey-macros"

[dependencies.tauri]
default-features = false
features = ["wry"]
version = "2.11.2"
